export declare const inBrowser: boolean;
export declare const isVoid: (value: any) => value is null;
export declare const isObject: (value?: any) => boolean;
export declare function defined(obj: any): boolean;
export declare function isNumeric(obj: any): boolean;
export declare function isEmpty(obj: any): boolean;
export declare function isEvent(obj: any): obj is Event;
export declare function isBlob(obj: any): obj is Blob;
export declare function isFile(obj: any): obj is File;
export declare function isPromise(obj: any): obj is Promise<any>;
export declare function isPrimitive(val: any): boolean;
export declare function isUrl(str: any): boolean;
export declare function isNode(obj: any): obj is Node;
export declare function isElement(obj: any): obj is Element;
export declare function isChildNode(parent: Node, child: Node): boolean;
export declare function isPosterityNode(parent: Node, child: Node): boolean;
export declare function isHTMLString(str: string): boolean;
